### ISSUE TITLE
How Does This work?

### ISSUE THREAD

**Issue by obvCirmaci** [Decencies/Vape#9]
Bro like wtff is this dll supposed to b

**Comment by Decencies** [comment]
> Bro like wtff is this dll supposed to b

If you did some research on your own, this DLL is a (work in progress) identical remake of the original Vape4DLL supplied to the user who has purchased vape through the websocket.

The DLL's purpose is to load the Java class files as well as do various other things which are pretty self explanatory, such as the reflection API [which you can find here](https://github.com/Decencies/Vape/blob/main/Vape4DLL/src/natives/reflection.cpp).
